name: Chromatic
run-name: Chromatic deploy
on: 
  push:
    branches: [ main, datepicker ]
  pull_request:
    branches: [ main ]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Publish to Chromatic
        uses: chromaui/action@v2
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}